#:schema https://mise.jdx.dev/schema/mise.json

[plugins]
	taplo = "https://github.com/Okeanos/asdf-taplo"

# See https://github.com/jdx/mise/blob/main/registry.toml for what is officially available
# Everything else is just declared as a reference to keep track of it.
[tools]
	editorconfig-checker = "3.3.0" # GitHub Actions sha256sum=923b80494b09b362d4fdb0d706913b67da0d60b4e2d34e5e346aa7e4118d6ab3
	gitleaks = "8.26.0"            # GitHub Actions sha256sum=32faa8a77f6ce4b483921072ea89f78a794ad1d96471f2ad6e01ad3b0ebafa00
	java = "17"
	lychee = "0.18.1"
	markdownlint-cli2 = "0.18.1"
	shellcheck = "0.10.0"
	shfmt = "3.11.0"
	taplo = "0.9.3"                # GitHub Actions sha256sum=889efcfa067b179fda488427d3b13ce2d679537da8b9ed8138ba415db7da2a5e
	yamllint = "1.37.1"
