name: Verify

# yamllint disable-line rule:truthy
on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run EditorConfig Checker
        run: |
          curl --fail --silent --show-error --location --output ec.tar.gz \
          https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.0.0/ec-linux-amd64.tar.gz
          tar -xzf ec.tar.gz
          chmod +x ./bin/ec-linux-amd64
          ./bin/ec-linux-amd64 --exclude .git
      - name: Run yamllint
        run: |
          pip install yamllint
          yamllint .
      - uses: ludeeus/action-shellcheck@2.0.0
      - uses: DavidAnson/markdownlint-cli2-action@v15
